### PR TITLE
gocode: add -unimported-packages flag

### PR DESCRIPTION
**Pull request by naoina**
`nsf/gocode` has `unimported-packages` option, but still not in this fork.
I backported that feature as a flag of client.

### CODE REVIEW

**Comment by frou** [comment]
https://github.com/nsf/gocode#options

This feature gives a nice boost to the usability of completions. I certainly noticed the absence of it when switching to this fork.

It dovetails nicely with editors that format-on-save. i.e. `gocode`'s completions help you explore and use the standard library, and `goimports` brings up the rear and takes care of the import declarations for what you've just been helped to type.

**Comment by stamblerre** [comment]
Thanks for putting this together! My only comment is can we separate the map into its own file (something like stdlib.go)?

**Comment by naoina** [comment]
@stamblerre I separated the conversion map into `stdlib.go`, and I force pushed.

**Comment by stamblerre** [comment]
Thanks!

**Pull request merged**
