### PR TITLE
Parse files in parallel and only parse buildable files

### PR DESCRIPTION
**Pull request by charlievieth**
This commit introduces two changes.  The first is to parse other package files in parallel.  The second is to only parse files that would be considered buildable by go/build.

Using go/build.Import() is relatively slow and cannot be parallelized (it must run before the parallel parse).  To get around using go/build, this commit adds a package 'buildutil', which is a slimmed down version of [github.com/charlievieth/buildutil](https://github.com/charlievieth/buildutil), that can quickly determine if a package should be included.  In order for 'buildutil' to respect the PackedContext passed in by the client - it was added as a field to suggest.Config, which is populated by the server.

### CODE REVIEW

**Comment by charlievieth** [comment]
Tests pass on Go versions 1.10.3 and go1.11.0 on Linux and Darwin.  Tests also pass on Linux with the latest development version of Go:

`go version devel +4545fea4fc Sat Sep 8 23:59:26 2018 +0000 linux/amd64`

**Comment by charlievieth** [comment]
There is a follow on PR to move `PackedContext` to a separate `context` package (commit: https://github.com/charlievieth/gocode/commit/bbaaca997d4bc67c3c7101c8ed86eee136b3ca55 - [branch](https://github.com/charlievieth/gocode/tree/mdempsky-move-packed-context)) that I will create if this is accepted.  

That will make the separation of concerns a little cleaner under the `internal` directory since `PackedContext` is now used by the `main`, `gbimporter` and `suggest` packages.

**Comment by charlievieth** [comment]
bump

**Comment by myitcv** [comment]
@charlievieth I suspect these changes will be superseded by an upcoming change that is currently being tested out in https://github.com/stamblerre/gocode, namely support for #46. 

That support uses the new [`go/packages`](https://godoc.org/golang.org/x/tools/go/packages).

cc @stamblerre and @matloob

**Comment by charlievieth** [comment]
SGTM.  Let me know if you'd like for me to close this PR (https://github.com/mdempsky/gocode/pull/54) and my other one (https://github.com/mdempsky/gocode/pull/55 - parse files in parallel) since [go/packages](https://godoc.org/golang.org/x/tools/go/packages) does that already.

**Comment by stamblerre** [comment]
Yeah, I'm sorry about this, but I think it may not be worth it to accept these PRs because of our planned migration to go/packages.

**Comment by charlievieth** [comment]
np, happy to close.

**Pull request closed without merging**
