### PR TITLE
Use import name if set else package name when qualifying types

### PR DESCRIPTION
**Pull request by myitcv**
Following discussion in #18; this is an alternative to #19 and is an implementation of option 3 from [this comment](https://github.com/mdempsky/gocode/issues/18#issuecomment-240154153)

Again, I've marked this as `[WIP]` and am trying it locally to see how things work out in `vim-go`

### CODE REVIEW

**Comment by myitcv** [comment]
@mdempsky having trialled this for a while it's now by far my preferred option.

The `tip` build is failing however because of two reasons:

1. an API surface change in `compress/zlib`
2. a change in the `go/*` packages that triggers change in behaviour that we need to handle (could well be parser related?)

As far as problem 1 is concerned we can either:

* find a stdlib package that is suitably interesting and relatively static (relatively cheap, easy?, sustainable?)
* make the test files `go version` dependent in some way (expensive-ish, moderately sustainable)
* include a test package as part of the `gocode` repo that we can control (moderately expensive, totally sustainable)

What approach would you like to follow? (I'm happy to help out in another PR to keep things separate)

As far as problem 2 is concerned, what I guess is a change in a `go/*` package causes the [this test case](https://github.com/mdempsky/gocode/blob/0b2050faba12fe2da80178f9ca5dd0cbf64f0db0/suggest/testdata/test.0029/test.go.in) to fail because the `fmt` names are not included in the candidate list. This boils down to [this logical expression](https://github.com/mdempsky/gocode/blob/0b2050faba12fe2da80178f9ca5dd0cbf64f0db0/suggest/suggest.go#L157) returning `true` at `tip`:

```go
			if !isPkgScope && obj.Pos() > pos {
				continue
			}
```

The names of the `fmt` package are correctly discovered at what I guess must be the file scope (hence `!isPkgScope` is true) but then `obj.Pos() > pos` is also true where in `go 1.7.3` and before it was not.

Truth be told, I've got no idea what's going on/was intended with the second operand... can you help steer me in the right direction?

**Comment by myitcv** [comment]
@mdempsky I've rebased this against `master` - any thoughts on whether you'd like to see this go in?

Thanks

**Comment by mdempsky** [comment]
Thanks for working on this, and sorry this PR has lingered so long.

You mention this is your preferred option out of the ones presented in #18. Do you mind elaborating why? In what ways do you find it an improvement over the status quo?

(For the record, it looks like the two other issues you pointed out were fixed in b3c2761.)

**Comment by myitcv** [comment]
@mdempsky 

> Thanks for working on this, and sorry this PR has lingered so long.

No problem at all.

> Do you mind elaborating why? In what ways do you find it an improvement over the status quo?

Of course.

If you consider [the test file](https://github.com/myitcv/gocode/blob/41d89c2d2c3604504b5a5de4d243453b60294e76/suggest/testdata/test.0065/test.go.in) that is part of this PR:

```go
package p

import (
	"fmt"
	banana "io"
)

var _ = fmt.@
```

If I ask for a completion at `@` then I would expect, given my renaming of the import of `"io"` to `banana`, to see suggestions in the context of the imports in the current file:

```
Found 25 candidates:
  func Errorf(format string, a ...interface{}) error
  func Fprint(w banana.Writer, a ...interface{}) (n int, err error)
  func Fprintf(w banana.Writer, format string, a ...interface{}) (n int, err error)
...
```

hence [the expected](https://github.com/myitcv/gocode/blob/41d89c2d2c3604504b5a5de4d243453b60294e76/suggest/testdata/test.0065/out.expected) output.

Otherwise, the suggestions would simply reference `io.*` - which, to my mind, is somewhat confusing given I've deliberately renamed the import of `"io"` in this file.

Given that in most situations people don't rename imports, this PR will have no effect. But where they do, I think it will offer suggestions that require less cognitive load to mentally parse.

**Pull request merged**
